# Generated by Django 5.2.3 on 2025-06-11 07:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='NetworkLine',
            fields=[
                ('line_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'network_lines',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
    ]
